### ISSUE TITLE
Migration from confluent to karapace

### ISSUE THREAD

**Issue by akhugsal** [Aiven-Open/karapace#268]
# What can we help you with?
I am planning to move from confluent to Karapace, was able to test a drop in replacement where I just pointed karapace to the existing schema topic that confluent was pointing to. Please note our backend/storage is in kafka. This worked well with karapace providing access using the same rest apis that confluent was providing.

I am trying to figure out if I can continue to run Karapace and confluent together till all apps migrate to Karapace if they both read and write to the same schema topic stored in kafka?

# Where would you expect to find this information?
Has anybody tried this before or what are your migration strategies?

**Comment by hackaugusto** [comment]
> I am trying to figure out if I can continue to run Karapace and confluent together till all apps migrate to Karapace if they both read and write to the same schema topic stored in kafka?

If you want to run both at the same time *with different schemas*, uou can configure the topic used by both Schema Registry and Karapace.

- [`kafkastore.topic` to configure Schema Registry](https://docs.confluent.io/platform/current/schema-registry/installation/config.html#kafkastore-topic)
- [`topic_name` for Karapace](https://github.com/aiven/karapace#configuration-keys)

If you want to use both with the same topic for schemas (the default), then I'd recommend disabling writing on one of these systems, otherwise you may end up with inconsistencies, because SR and Karapace do not create a consensus.
