### ISSUE TITLE
schema reader can not replay schema topic

### ISSUE THREAD

**Issue by dada-engineer** [Aiven-Open/karapace#812]
# What happened?

We have upgraded karapace from version 3.10.4 to 3.10.5 (and 3.10.6 respectively) but the schema reader hangs while replaying showing a progress of minus 0.39 percent.

`karapace.schema_reader	schema-reader	INFO    	Replay progress (0.29): -1/254 (-0.39 %)`

So the schemas are not replayed and nothing happens.

# What did you expect to happen?

I would expect to start at the first schema message in the topic so that all schemas can be rebuilt.

# What else do we need to know?

Running with official docker image v3.10.5 and 3.10.6

**Comment by matyaskuti** [comment]
@dada-engineer Could you provide more of the logs? Is there anything unusual before the replay progress log lines?

**Comment by dada-engineer** [comment]
Not that I can see @matyaskuti. Some rejoining but this is probably because the k8s pod running rolled over.

[Explore-logs-2024-02-06 15_54_34.txt](https://github.com/Aiven-Open/karapace/files/14182014/Explore-logs-2024-02-06.15_54_34.txt)

**Comment by matyaskuti** [comment]
@dada-engineer Thanks for the logs, a couple more things:

* Is there any custom (ie. not default) configuration of the schema registry that you are running, could you share these?
* The issue persists even when Karapace is restarted?
* If the replay progress is stuck on -1, it means that the schema reader's consumer can make a connection to the cluster, read the watermark offsets, but doesn't receive any messages from the schemas topic despite polling constantly...
* ...is it possible that the messages in the topic got deleted/compacted (eg. because of the retention period)?

**Comment by dada-engineer** [comment]
* config is pretty standard except for SSL cert auth but same config is working with 3.10.4
* Restarting does not fix it
* Messages are not retained in this topic and working with 3.10.4

As everything is working in 3.10.4 I am unsure it's indeed a config issue

**Comment by michael-zucchetta** [comment]
Hi, 

I encountered the same issue passing from 3.9.0 to 3.10.3, then I tried to update to 3.10.8, and I obtained a similar situation:

```
kafka.coordinator   	Thread-2	INFO    	(Re-)joining group karapace-registry
karapace.schema_reader	schema-reader	INFO    	Replay progress (0.2): -1/1029 (-0.1 %)
karapace.schema_reader	schema-reader	INFO    	Replay progress (0.2): -1/1029 (-0.1 %)
karapace.schema_reader	schema-reader	INFO    	Replay progress (0.2): -1/1029 (-0.1 %)
karapace.schema_reader	schema-reader	INFO    	Replay progress (0.2): -1/1029 (-0.1 %)
```

Setting the version to 3.10.4, seems to have worked
From https://github.com/Aiven-Open/karapace/releases/tag/3.10.4:

```
Revert "Replace sync Kafka consumers with confluent_kafka one"
```
Could it be why 3.10.4 works for us, and not 3.10.3, nor, possibly 3.10.5 or 3.10.6?

I don't have any particular configuration

**Comment by dada-engineer** [comment]
I have an hour at Monday of free time I might investigate here but couldn't setting max(beginning_offset - 1, 0) in this line resolve the issue?

https://github.com/Aiven-Open/karapace/blob/main/karapace%2Fschema_reader.py#L236-L241

@matyaskuti what's the hint regarding old offset handling? Is this still important?

**Comment by matyaskuti** [comment]
@michael-zucchetta Indeed it seems like the issue is related to the switch to the confluent-kafka-python based consumer. Version 3.10.4 had that reverted to a bug in backups and 3.10.5 reintroduced it after fixing the original issue.

@dada-engineer 

> I have an hour on Monday of free time I might investigate here but couldn't setting max(beginning_offset - 1, 0) in this line resolve the issue?

That would be a fix for the percentage calculation, yes, but if the replay is stuck on not reading records from the schemas topic, it would only result in `Replay progress (0.29): 0/254 (0.0 %)` in the logs, similarly repeated.

The adjustment (or lack of it) of the `beginning_offset` would give a similar result I think.

However I can't reproduce the consumer not reading anything despite being able to fetch the watermark offsets. Could you perhaps provide some info of the records in your schemas topic? Structure, size, maybe a few examples. I'm suspicious of [this](https://github.com/Aiven-Open/karapace/blob/main/karapace/schema_reader.py#L318-L320) code skipping messages with `None` keys, which was added alongside of the confluent-kafka-python consumer.

**Comment by dada-engineer** [comment]
@matyaskuti sorry to come back late.

We do have keys in json format

```
{
	"keytype": "SCHEMA",
	"subject": "some.topic.v1-value",
	"version": 1,
	"magic": 1
}
```

It might be the consumer not getting any messages from the topic (don't know why as I see successfullt joined group msg so I guess auth works).

As of local testing the consumer does indeed not get any messages but I do not know why. The difference between 3.10.4 and later versions is in the working 3.10.4 I see OffsetRequests and FetchRequests in the logs. I do not see them in the latest version.

**Comment by matyaskuti** [comment]
In the new release [3.11.2](https://github.com/Aiven-Open/karapace/releases/tag/3.11.2) I've added extra logging, if there is some error directly during consumption, that should surface, @dada-engineer, if you could run that version and share the replay logs, that'd be great.

**Comment by dada-engineer** [comment]
Sure, thanks I did not see a difference in logs on first glance but here you go:

[logs.txt](https://github.com/Aiven-Open/karapace/files/14435936/logs.txt)

**Comment by matyaskuti** [comment]
In the new log file, on L47: `karapace.schema_reader  schema-reader   WARNING     Empty message key when consuming from topic None, error: KafkaError{code=GROUP_AUTHORIZATION_FAILED,val=30,str="FindCoordinator response error: Group authorization failed."}` Ie. when trying to consume there is a group authorization error from the cluster.

Could you double check your auth and ACLs?

**Comment by dada-engineer** [comment]
Oh cool thanks a lot. Is there any docs what ACLs are required?

**Comment by dada-engineer** [comment]
I have the ACLs applied according to [Confluent schema registry requirements](https://docs.confluent.io/platform/current/schema-registry/security/index.html#authorizing-access-to-the-schemas-topic) but this does not work.

Also in the log states msg.topic is None. How come? And I only see this message once, shouldn't this be printed repeatedly? How many partitions should the topic have btw?

**Comment by matyaskuti** [comment]
> Also in the log states msg.topic is None. How come? And I only see this message once, shouldn't this be printed repeatedly?

The message topic is `None` here because it's not a topic related issue (see below). Because of the underlying confluent-kafka-python library (the new client after version 3.10.4) we get this error message once, since the consumer from the library not only raises exceptions, but returns "error messages", which only happen once. (We can definitely improve how that's handled in this particular situation.)

> How many partitions should the topic have btw?

Because the schemas topic must be ordered, there should only be one partition.


After digging a little bit, it seems that the issue is not with topic related permissions, but consumer group related ones. After switching to confluent-kafka-python, the schema reader's consumer is part of a single-member consumer group (the library doesn't allow out-of-group consumers as kafka-python did before).

When trying to find the group coordinator, the consumer receives an error that it's lacking the permission to do so - [describe operation on the group resource](https://docs.confluent.io/platform/current/kafka/authorization.html#group-resource-type-operations).

The group ID is prefixed with `karapace-autogenerated-`, followed by a random string 6 characters long.

Confluent-kafka-python uses `librdkafka` underneath, here is a related [issue](https://github.com/confluentinc/confluent-kafka-go/issues/534) in another wrapper library of librdkafka.

**Comment by dada-engineer** [comment]
@matyaskuti thanks a lot for explaining / debugging / helping me ❤️ 

The issue has been indeed that there is now an additional group that needs group describe and read permissions. It is working now. 🎉 

Is there any preferred docs and should this ticket be used to document the required ACLs for the schema registry setup? 🤔

**Comment by dada-engineer** [comment]
@matyaskuti LGTM

Thank you very much for your help and your work on karapace 👍🏻
